### ISSUE TITLE
Can't get composer to install it

### ISSUE THREAD

**Issue by godbout** [wearerequired/harvest-api-php-client#14]
Whatever combination I'm trying there's issues with constraints between  the guzzle adapter.

```bash
Problem 1
    - wearerequired/harvest-api-php-client dev-master requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.1, v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.0 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - php-http/guzzle6-adapter v2.0.1 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[v2.0.0].
    - Can only install one of: php-http/httplug[v2.0.0, v1.1.0].
    - Can only install one of: php-http/httplug[v1.1.0, v2.0.0].
    - wearerequired/harvest-api-php-client dev-master requires php-http/httplug ^1.1 -> satisfiable by php-http/httplug[v1.1.0].
    - Installation request for wearerequired/harvest-api-php-client dev-master -> satisfiable by wearerequired/harvest-api-php-client[dev-master].
```

Any chance to update the constraints? Add a tag version also maybe?

**Comment by ocean90** [comment]
Thanks for report @godbout. I'll check what's broken here. Haven't created a tag yet since it's still in development but I guess a 0.1.0 should be fine for now.

**Comment by godbout** [comment]
Thanks @ocean90! Yeah, versions before 1.0.0 are expected not to be stable, so I think it's good. Although it's just an idea. Let me know if you need more info for the constraint issue. I'm building an Alfred Workflow that handles several types of timers and Harvest is one of them. Would love to use your package!

**Comment by ocean90** [comment]
@godbout I updated the HTTPlug dependency to 2.0 so it should work now. 0.1.0 is also tagged.

**Comment by godbout** [comment]
Excellent. Thank you!
