### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by wsdnathan** [wearerequired/harvest-api-php-client#29]
composer.json requires
"php": "^8.0",
"php-http/guzzle7-adapter": "^0.1.1"

**Comment by wsdnathan** [comment]
Looks like others are using "guzzlehttp/guzzle": "^7.2"

**Comment by ocean90** [comment]
Hi @wsdnathan, are you able to test #30 which should make the library compatible with PHP 8?

**Comment by wsdnathan** [comment]
I am able to test once a release is tagged

**Comment by wsdnathan** [comment]
@ocean90 any word on tagging a release for PHP8 compat?

**Comment by ocean90** [comment]
@wsdnathan You should be able to install and test it with 


`composer require wearerequired/harvest-api-php-client:dev-php8 php-http/guzzle7-adapter`

**Comment by wsdnathan** [comment]
@ocean90 I have tested that it both installs and works with Laravel 8 Nova project.
`  - Installing wearerequired/harvest-api-php-client (dev-php8 d2af3b0): Cloning d2af3b0c20 from cache`

I will note that installing it produced a bunch of these types of warnings:
`Class App\Nova\Project located in ./app/Nova/Resources/Project.php does not comply with psr-4 autoloading standard. Skipping.`

**Comment by wsdnathan** [comment]
Whoops I noted some warnings in my previous comment but that was an unrelated namespacing issue. Think this is good to go after further testing.
